### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

### ISSUE THREAD

**Issue by Vikrant-Deshmukh** [catthatcodes/car-damage-assessment#3]
Traceback (most recent call last):
  File "/Users/vikrant/Downloads/Car/catthatcodes/app/app.py", line 7, in <module>
    from pipeline import pipeline
  File "/Users/vikrant/Downloads/Car/catthatcodes/app/pipeline/pipeline.py", line 8, in <module>
    graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

**Comment by kartikone** [comment]
https://github.com/keras-team/keras/issues/12783

**Comment by Patrick-Vogt** [comment]
@Vikrant-Deshmukh  Have you been able to solve this?

**Comment by Midnight93** [comment]
Try with this one:

`tf.compat.v1.get_default_graph()`

The problem is the compatibility :)
